### ISSUE TITLE
What is the startup scene like in Bogotá? 

### ISSUE THREAD

**Issue by CarlMungazi** [camilonova/ama#2]

**Comment by camilonova** [comment]
Hi Carl, at this time is becoming very interesting, thank you for asking.

Geographically Bogotá is the best place to enter into South America, we have a lot of local and international companies based here running their businesses on other countries like Venezuela, Ecuador, Peru, and all the others. This situation attracted a lot of foreign talent to live and work here and made our cultural environment more diverse and powerful. I think we do have the best business people working in Bogotá and that's a unique opportunity for new business to grow.

I'd visited some countries where all the basic problems are already solved and there are not many options for solving real life problems, like real startups do. Colombia is moving from away from being a non developed country, we have a lot of foreign investments, international business policies, and a safer environment. Having all this at the same time seems like a recipe for an amazing opportunity to start a startup.

We now have a lot of meetups, coworking spaces, accelerators, investors and government help to encourage people to work on our local problems. More and more people from North America and Europe are coming here because of the huge opportunities we have, and you can see them walking on the streets or attending local meetups, or even raising money https://www.kickstarter.com/projects/movacycling/mova-cycling-jacket-your-essential-jacket-for-urba.

Living here is great, we do have great people, beautiful landscapes a warm and stable weather all the time, local people are very friendly with foreigns, and you will see people talking and smiling all around.

There are lots of things going on, you can take a peek in here https://trello.com/b/zPPxLrK2/mapa-del-emprendimiento-en-colombia but the best thing you can do is to come here and see it for yourself.

When you decide to come let me know, I can show you around.
